# Generated by Django 3.1.1 on 2020-09-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_duration',
            field=models.TimeField(blank=True, default='2.47.00'),
            preserve_default=False,
        ),
    ]
