# Generated by Django 3.1.1 on 2020-09-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_auto_20200926_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_enroll',
            field=models.BooleanField(default=False),
        ),
    ]
