# Generated by Django 3.1.1 on 2020-09-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherEnroll', '0004_auto_20200920_2145'),
        ('CourseMaterial', '0001_initial'),
        ('Teacher', '0002_quiz_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='CourseMaterial.coursematerial'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(related_name='interested_students', to='TeacherEnroll.TeacherEnroll'),
        ),
    ]
