# Generated by Django 3.1.1 on 2020-09-26 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UploadLecture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadlecture',
            name='Image',
        ),
        migrations.AddField(
            model_name='uploadlecture',
            name='Text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadlecture',
            name='Pdf',
            field=models.FileField(blank=True, null=True, upload_to='PDF/'),
        ),
        migrations.AlterField(
            model_name='uploadlecture',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='Videos/'),
        ),
        migrations.AlterField(
            model_name='uploadlecture',
            name='username',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_trainer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
