# Generated by Django 3.1.1 on 2020-09-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherEnroll', '0003_teacherenroll_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherenroll',
            name='Batch',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherenroll',
            name='CourseDuration',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherenroll',
            name='CourseStartDate',
            field=models.DateField(default='2020-10-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherenroll',
            name='is_publish',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
