# Generated by Django 3.0.8 on 2020-07-28 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseCode', models.IntegerField(help_text='please enter a number ')),
                ('CourseName', models.CharField(max_length=150)),
                ('CourseStartDate', models.DateField()),
                ('CourseDuration', models.CharField(help_text='6 months', max_length=15)),
                ('picture', models.ImageField(default='default.jpg', upload_to='Course_Pic/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(max_length=100)),
                ('CourseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GovernmentEmployee.Course')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
