# Generated by Django 3.1.1 on 2020-09-11 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GovernmentEmployee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='CourseName',
            field=models.ForeignKey(limit_choices_to={'CourseName': 'username'}, on_delete=django.db.models.deletion.CASCADE, to='GovernmentEmployee.course'),
        ),
    ]
