# Generated by Django 3.1.1 on 2020-09-11 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GovernmentEmployee', '0002_auto_20200911_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='CourseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GovernmentEmployee.course'),
        ),
    ]
