# Generated by Django 3.1.1 on 2020-09-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovernmentEmployee', '0003_auto_20200911_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CourseCode',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CourseDuration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CourseStartDate',
        ),
        migrations.AddField(
            model_name='course',
            name='Description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
    ]
