# Generated by Django 3.1.1 on 2020-09-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
        ('accounts', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='MinistryName',
        ),
        migrations.AddField(
            model_name='user',
            name='MinistryName',
            field=models.ManyToManyField(blank=True, null=True, to='SuperAdmin.Ministry'),
        ),
    ]
