# Generated by Django 3.1.1 on 2020-10-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
        ('accounts', '0008_auto_20201003_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='MinistryName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.ministry'),
        ),
    ]
