# Generated by Django 3.1.1 on 2020-09-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
        ('accounts', '0006_auto_20200921_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='MinistryName',
            field=models.ManyToManyField(blank=True, to='SuperAdmin.Ministry'),
        ),
    ]
