# Generated by Django 3.1.1 on 2020-12-28 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institute Name ')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Degree')),
                ('result', models.FloatField(blank=True, null=True, verbose_name='Result')),
                ('Major', models.CharField(blank=True, max_length=100, null=True, verbose_name='Major')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_student', models.BooleanField(default=False, verbose_name='I currently study here')),
                ('Description', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
