# Generated by Django 3.1.1 on 2020-09-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadLecture', '0002_auto_20200926_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlecture',
            name='Video',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
